services:
  vibes-redis-server:
    image: vibes-redis-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    env_file:
      - .env
