services:
  vibes-ds-server:
    image: vibescontainer/vibes-ds-server:1.0.0
    container_name: vibes-redis-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./cache:/app/cache
    restart: unless-stopped
    env_file:
      - .env
