version: "3.8"

services:
  vibes-ds-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibes-ds-server
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/app/data
    restart: unless-stopped

volumes:
  data_volume:
